#! /bin/bash
APPNAME="smartws"
SERVER_NAME=""
SERVER_PORT=""
while [ -z "$SERVER_NAME" ]; do
	read -p "$Enter server domain : " SERVER_NAME
done
while [ -z "$SERVER_PORT" ]; do
	read -p "$Enter ssh port : " SERVER_PORT
done
apt update
# install xray-core
# installed: /etc/systemd/system/xray.service
# installed: /etc/systemd/system/xray@.service
# 
# installed: /usr/local/bin/xray
# installed: /usr/local/etc/xray/*.json
# 
# installed: /usr/local/share/xray/geoip.dat
# installed: /usr/local/share/xray/geosite.dat
# 
# installed: /var/log/xray/access.log
# installed: /var/log/xray/error.log
if ! ls /etc/systemd/system/xray.service &> /dev/null; then
	bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
fi
# first backup old smartws
if ls /opt/$APPNAME &> /dev/null; then
	cp -r /opt/$APPNAME /opt/${APPNAME}_old
fi
# download smartws zip and extract it to /opt/smartws/
if ls /tmp/$APPNAME.zip &> /dev/null ; then
	read -p "$APPNAME.zip is already exists. Do you want to download it again ? y(es),n(o)" dowload_zip_again
	if [[ "${dowload_zip_again,,}" == "y" ]] || [[ "${dowload_zip_again,,}" == "yes" ]]; then
		wget -O /tmp/$APPNAME.zip https://github.com/mostafa3dmax/smart_tunnel/raw/main/smartws.zip
	fi
else
	wget -O /tmp/$APPNAME.zip https://github.com/mostafa3dmax/smart_tunnel/raw/main/smartws.zip
fi

rm -r /opt/$APPNAME &> /dev/null
unzip /tmp/$APPNAME.zip -d /opt/$APPNAME 1> /dev/null
chown root /opt/$APPNAME

# backup old smartws config
if ls /etc/opt/smartws/config &> /dev/null; then
	mv /etc/opt/smartws/config /etc/opt/smartws/config_old
else
	mkdir /etc/opt/$APPNAME &> /dev/null
fi

# copy smartws config to /opt/$APPNAME/config/
if ls /etc/opt/$APPNAME/config &> /dev/null; then
	read -p "$APPNAME config file is already exists. Do you want reaplace it ? y(es),n(o)" replace_config
	if [[ "${replace_config,,}" == "y" ]] || [[ "${replace_config,,}" == "yes" ]]; then
		cp /opt/$APPNAME/config/config /etc/opt/$APPNAME/config
	fi
else
	cp /opt/$APPNAME/config/config /etc/opt/$APPNAME/config
fi
# copy xray config to /usr/local/etc/xray/*
cp /opt/$APPNAME/config/xray_config.json /usr/local/etc/xray/config.json

# backup old smartws script
if ls /usr/local/bin/smartws &> /dev/null; then
	mv /usr/local/bin/smartws /usr/local/bin/smartws_old
fi
# link new smartws script to /usr/local/bin
ln -f -s /opt/$APPNAME/script/smartws /usr/local/bin/smartws
chmod +x /usr/local/bin/smartws
chown root /usr/local/bin/smartws

# remove old service
rm /etc/systemd/system/smartws.service &> /dev/null

# link smartws service
groupadd smartws 2> /dev/null
ln -f -s /opt/$APPNAME/service/smartws.service /etc/systemd/system/smartws.service

# copy nginx config
cp /opt/$APPNAME/config/nginx_config /etc/nginx/sites-available/$SERVER_NAME
# change nginx config 
sed -i -e 's#sh3.goolha.tk#'$SERVER_NAME'#' /etc/nginx/sites-available/$SERVER_NAME
echo "nginx config updated"

# modify xray service user
sed -i -e 's/User=nobody/User=root/' /etc/systemd/system/xray.service
echo "xray service user updated"
# change smartws config parameters 
sed -i -e 's#"port": 2232#"port": '"$SERVER_PORT"'#' /etc/opt/$APPNAME/config
sed -i -e 's#"sh3.goolha.tk#'"$SERVER_NAME"'#' /etc/opt/$APPNAME/config
echo "smartws config updated"

# create xray clients from trojan-go passwords
/bin/java -jar /opt/$APPNAME/script/trojan2xray.jar /etc/trojan-go/config.json /usr/local/etc/xray/config.json
echo "trojan passwords copied to xray config"

systemctl daemon-reload

rm /tmp/$APPNAME.zip
systemctl enable smartws.service
systemctl stop smartws.service
systemctl start smartws.service
systemctl enable xray.service
systemctl stop xray.service
systemctl start xray.service
systemctl restart nginx.service